gitname: Build

branch:

on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build
    needs: [prerequisites]
    runs-on: ubuntu-latest
    continue-on-error: false
    steps:
    - name: Tests
      run: echo Building
