name: Build

branch:

on:
  push:
    branches:
      - main
jobs:
  prerequisites:
    environment: shared
    env:
      ENABLED: ${{ secrets.ENABLED }}
    runs-on: ubuntu-latest
    if: ${{ ENABLED == 'true'}}
    steps:
      - name: Enabled
        run: echo hi
  build:
    name: Build
    needs: [prerequisites]
    runs-on: ubuntu-latest
    continue-on-error: false
    steps:
    - name: Tests
      run: echo Building
