name: Build

on: push

jobs:
  prerequisites:
    runs-on: ubuntu-latest
    if: github.repository == 'rwinch/github-actions-context'
    steps:
      - name: Enabled
        run: echo Enabled
  build:
    name: Build
    needs: [prerequisites]
    runs-on: ubuntu-latest
    continue-on-error: false
    steps:
    - name: Tests
      run: echo Building
